=== ememargv/Proyecto-Intermodular-Libros/Proyecto-Intermodular-Libros/src/XML/biblioteca.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="biblioteca">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="libro" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titulo" type="xs:string"/>
                            <xs:element name="autor" type="xs:string"/>
                            <xs:element name="genero" type="xs:string"/>
                            <xs:element name="puntuacion" type="xs:integer"/>
                            <xs:element name="estado" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:integer" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ememargv/Proyecto-Intermodular-Libros/Proyecto-Intermodular-Libros/src/XML/biblioteca.xml
<?xml version="1.0" encoding="UTF-8"?>
<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="biblioteca.xsd">
    <libro id="1">
        <titulo>El Imperio Final</titulo>
        <autor>Brandon Sanderson</autor>
        <genero>Fantasía</genero>
        <puntuacion>5</puntuacion>
        <estado>Leído</estado>
    </libro>
    <libro id="2">
        <titulo>Rehén</titulo>
        <autor>Guy Delisle</autor>
        <genero>Novela Gráfica</genero>
        <puntuacion>4</puntuacion>
        <estado>Leyendo</estado>
    </libro>
</biblioteca>
